"use strict";

let actions = [
  {
    id: "copy",
    affordance: chrome.i18n.getMessage("action_affordance_copy"),
    label: chrome.i18n.getMessage("action_label_copy"),
    interactive: true,
    context: "all",
    active: true,
  },
  {
    id: "search",
    affordance: chrome.i18n.getMessage("action_affordance_search"),
    label: chrome.i18n.getMessage("action_label_search"),
    interactive: true,
    context: "all",
    active: true,
  },
  {
    id: "call",
    affordance: chrome.i18n.getMessage("action_affordance_call"),
    label: chrome.i18n.getMessage("action_label_call"),
    interactive: true,
    context: "phone",
    active: true,
  },
  {
    id: "email",
    affordance: chrome.i18n.getMessage("action_affordance_email"),
    label: chrome.i18n.getMessage("action_label_email"),
    interactive: true,
    context: "email",
    active: true,
  },
  {
    id: "download",
    affordance: chrome.i18n.getMessage("action_affordance_download"),
    label: chrome.i18n.getMessage("action_label_download"),
    interactive: true,
    context: "all",
    active: true,
  },
  {
    id: "youtube",
    affordance: chrome.i18n.getMessage("action_affordance_youtube"),
    label: chrome.i18n.getMessage("action_label_youtube"),
    interactive: true,
    context: "all",
    active: false,
  },
  {
    id: "maps",
    affordance: chrome.i18n.getMessage("action_affordance_maps"),
    label: chrome.i18n.getMessage("action_label_maps"),
    interactive: true,
    context: "all",
    active: false,
  },
  {
    id: "wikipedia",
    affordance: chrome.i18n.getMessage("action_affordance_wikipedia"),
    label: chrome.i18n.getMessage("action_label_wikipedia"),
    interactive: true,
    context: "all",
    active: false,
  },
  {
    id: "speak",
    affordance: chrome.i18n.getMessage("action_affordance_speak"),
    label: chrome.i18n.getMessage("action_label_speak"),
    interactive: true,
    context: "all",
    active: false,
  },
  {
    id: "words",
    affordance: "%words%",
    label: chrome.i18n.getMessage("action_label_words"),
    interactive: false,
    context: "all",
    active: true,
  },
  {
    id: "characters",
    affordance: "%characters%",
    label: chrome.i18n.getMessage("action_label_characters"),
    interactive: false,
    context: "all",
    active: true,
  },
];
